### ISSUE TITLE
Can u share detect.py code and instructions how to run .pt model in windows please

### ISSUE THREAD

**Issue by raviyellani** [MDhamani/Traffic-Sign-Recognition-Using-YOLO#1]
Can u share detect.py code and instructions how to run .pt model in windows please

**Comment by MDhamani** [comment]
Here's the detect.py file. 
[detect.txt](https://github.com/MDhamani/Traffic-Sign-Recognition-Using-YOLO/files/7812740/detect.txt) (just change the extension to .py)
You can normally run the detect.py file using "python detect.py --weights best_93.pt --source 0".
 I also have a [video](https://www.youtube.com/watch?v=FAijtrQ28bA). showcasing the model and its performance.  
If you still have any questions or queries, reach out to me at any time.
