### ISSUE TITLE
no module named 'utils.datasets'

### ISSUE THREAD

**Issue by emrehankaraoglu** [MDhamani/Traffic-Sign-Recognition-Using-YOLO#2]
When I try to run the detect.py script I got error like that: from utils.datasets import LoadStreams, LoadImages
ModuleNotFoundError: No module named 'utils.datasets'

I have no idea what to do. I need help at that point. 
Thanks

**Comment by MDhamani** [comment]
You'll need to clone [ultralytics/yolov5](https://github.com/ultralytics/yolov5) repo, and replace the detect.py with the one in this repo

Let me know if you have any other issues. Happy to help.

**Comment by G0ldi98** [comment]
Hello, I have the same problem. The repo is cloned and the detect.py file is replaced. The error still exists. So far I have not found a solution.

Thanks for the help

**Comment by MDhamani** [comment]
I have updated the detect.py in the repo. It should work now. Give it a try.
