### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lordfarquad3211** [MDhamani/Traffic-Sign-Recognition-Using-YOLO#3]
Hello , from where do i get the annotated data in yolo format ? 
Thank you

**Comment by MDhamani** [comment]
I got the dataset from [here](https://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset)

And then I used the code in one of my [notebooks](https://github.com/MDhamani/Traffic-Sign-Recognition-Using-YOLO/blob/main/Traffic%20Sign%20Recognition%20Using%20YOLO.ipynb) to convert it into yolo format. 

Let me know if you have any other questions. Happy to help.
