### ISSUE TITLE
Following files are missing

### ISSUE THREAD

**Issue by tomid9999** [MDhamani/Traffic-Sign-Recognition-Using-YOLO#4]
I was going through the python notebook, in the training command i.e. 
'!./darknet/darknet detector train labelled_data.data yolov3-tiny_custom.cfg backup/yolov3-tiny_custom_best.weights -dont_show -map'
we would be requiring the following files:-
yolov3-tiny_custom_best.weights,yolov3-tiny_custom.cfg
Please provide these files or let me know where to get them from.

**Comment by MDhamani** [comment]
Here are the files : [weights](https://mega.nz/file/GINRlYpB#IFM62s4G0VMUYyIJlQH6rpLxtZpdQFj2e9lVOyeRj0I) and [cfg](https://mega.nz/file/zNdCyLzY#GXXuU6_E2wkfwAixJpPOzpXxrXub4UyEa9I861qb5M8).

You can also find other related files [here](https://github.com/pjreddie/darknet)

Let me know if you need anything else.
